### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by FJFernandezE** [e107translations/Translator-Information#3]
No puedo traducir el cms a Español, me dice el siguiente error:

Unauthorized acces!

**Comment by FJFernandezE** [comment]
Como puedo cambiar el lenguaje manualmente

**Comment by Moc** [comment]
@FJFernandezE Hi, please post your questions in English. 

- Are you using the latest version of e107? 
- Does the installation work correctly in English? 

Please make sure your e107 installation is running fine in English, before attempting to translate. Then follow the steps are instructed here: https://github.com/e107translations/Translator-Information#the-translation-process



> Como puedo cambiar el lenguaje manualmente

You can change the language manually through the database. Please be careful when doing this. The preference you are looking for are `sitelanguage` and `adminlanguage`. They are located in the `SitePrefs` row in the `e107_core` table.
